### Register a new user
POST https://localhost:8443/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "name": "user",
    "email": "user50@mail.com",
    "password": "password",
    "password_confirm": "password",
    "avatar": "https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50"
}

### Login a user
POST https://localhost:8443/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "user50@mail.com",
    "password": "password"
}

### Logout a user
GET https://localhost:8443/api/auth/logout HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODcyNzEwMzIsImlhdCI6MTY4NzI2NzQzMiwibmJmIjoxNjg3MjY3NDMyLCJzdWIiOiI4OWY0N2IxMi0yMTA2LTQxMmUtOWVhYy1jYjMwMjAzOGUxOGQifQ.jHYtwdEujx0FRy6L-x5QnDEf4KX0alscTf1ilBFcEec


### Get Current User
GET https://localhost:8443/api/auth/getCurrentUser HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODc2NTAzMzQsImlhdCI6MTY4NzQzNDMzNCwiaXNzIjoidGVzdCIsIm5iZiI6MTY4NzQzNDMzNCwic3ViIjoiYWU1MTgyYTctNzkzNy00MTExLTkzZTMtNTZkYTE0YzBjNTZmIn0.71Wz3QdLvMzED2lClCQ9-q1kWFcCgTh3hRReac1MVcc
