### Register
POST http://localhost:8080/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "name": "user",
    "email": "user2@mail.com",
    "password": "password",
    "password_confirm": "password",
    "avatar": "https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50"
}

### Login
POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "user2@mail.com",
    "password": "password"
}

### Logout
GET http://localhost:8080/api/auth/logout HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODcyNzEwMzIsImlhdCI6MTY4NzI2NzQzMiwibmJmIjoxNjg3MjY3NDMyLCJzdWIiOiI4OWY0N2IxMi0yMTA2LTQxMmUtOWVhYy1jYjMwMjAzOGUxOGQifQ.jHYtwdEujx0FRy6L-x5QnDEf4KX0alscTf1ilBFcEec


### Get Current User
GET http://localhost:8080/api/auth/getCurrentUser HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODcyNzEwMzIsImlhdCI6MTY4NzI2NzQzMiwibmJmIjoxNjg3MjY3NDMyLCJzdWIiOiI4OWY0N2IxMi0yMTA2LTQxMmUtOWVhYy1jYjMwMjAzOGUxOGQifQ.jHYtwdEujx0FRy6L-x5QnDEf4KX0alscTf1ilBFcEec
