### Get All Users
GET https://localhost:8443/api/user?page=5&size=25 HTTP/1.1
Content-Type: application/json

### Get User By Id
GET https://localhost:8443/api/user/f3358c25-3b72-42a5-bcd1-ba3f46ff1203 HTTP/1.1

### Get register schema
GET https://localhost:8443/api/schema/SignUpInput HTTP/1.1
